//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework_EF_Test.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id_Account { get; set; }
        public int APlace { get; set; }
        public string AObjName { get; set; }
        public int AInvNum { get; set; }
        public System.DateTime ADate { get; set; }
        public int AUsage { get; set; }
        public int APrice { get; set; }
        public int ACount { get; set; }
        public int ASum { get; set; }
        public string AStatus { get; set; }
        public int WorkerId_Worker { get; set; }
    
        public virtual Worker WorkerNav { get; set; }
    }
}
